version: 2
builds:
  - id: bka-backend
    main: ./main.go
    goos:
      - linux
      - windows
    goarch:
      - amd64
    goamd64:
      - v1

archives:
  - id: archive
    ids: [ bka-backend ]
    formats: [ binary ]
    name_template: "bka-backend"